# Generated by Django 3.2.12 on 2022-03-11 07:23

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('created', 'created'), ('opened', 'opened'), ('packing', 'packing'), ('ready to ship', 'ready to ship'), ('shipped', 'shipped'), ('delivered', 'delivered')], default=('created', 'created'), max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=600)),
                ('product_type', models.CharField(choices=[('Apparels', 'Apparels'), ('Awards & Recognition', 'Awards & Recognition'), ('Bags & Luggage', 'Bags & Luggage'), ('Electronics', 'Electronics'), ('Combo', 'Combo'), ('Office & Stationary', 'Office & Stationary'), ('Premium Gifts', 'Premium Gifts'), ('Promotional Gifts', 'Promotional Gifts'), ('Leather & Leatherites', 'Leather & Leatherites'), ('Homeware', 'Homeware'), ('Drinkware', 'Drinkware'), ('Festivals', 'Festivals'), ('Covid-19', 'Covid-19'), ('Eco Friendly', 'Eco Friendly')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('options', jsonfield.fields.JSONField(default=dict)),
                ('highlights', models.TextField(max_length=800)),
                ('specifications', jsonfield.fields.JSONField(default=dict)),
                ('offers', models.TextField(max_length=200)),
                ('gender', models.CharField(max_length=2)),
                ('category', models.CharField(choices=[('Lapel Pins', 'Lapel Pins'), ('Gift Sets', 'Gift Sets'), ('Salvers', 'Salvers'), ('Diary & Note Pads', 'Diary & Note Pads'), ('Security Uniforms', 'Security Uniforms'), ('Plants', 'Plants'), ('Folders', 'Folders'), ('Travel Accessories', 'Travel Accessories'), ('Rollers', 'Rollers '), ('Water Bottles', 'Water Bottles'), ('Trophy-Fiber', 'Trophy-Fiber'), ('Frames', 'Frames'), ('Powerbanks', 'Powerbanks'), ('Tech Accessories', 'Tech Accessories'), ('Laptop Bags', 'Laptop Bags'), ('Bluetooth Speakers', 'Bluetooth Speakers'), ('Short', 'Short'), ('Formal Shirt', 'Formal Shirt'), ('Lanyards', 'Lanyards'), ('Office & Desktops', 'Office & Desktops'), ('Mugs', 'Mugs'), ('Sanitizer', 'Sanitizer'), ('Pouches', 'Pouches'), ('Earphones', 'Earphones'), ('Wellness Gifts', 'Wellness Gifts'), ('Gadgets', 'Gadgets'), ('Hand Bagags', 'Hand Bagags'), ('Aroma Candles', 'Aroma Candles'), ('Sippers', 'Sippers'), ('Timekeepers', 'Timekeepers'), ('Cookies and Cakes', 'Cookies and Cakes'), ('Headphones', 'Headphones'), ('Personal Gifts - Key chains', 'Personal Gifts- Key chains'), ('Plaques', 'Plaques'), ('Overnighters', 'Overnighters'), ('Gift Packaging', 'Gift Packaging'), ('Strolley', 'Strolley'), ('Flowers & Plants', 'Flowers & Plants'), ('Others', 'Others'), ('Covid Kit', 'Covid Kit'), ('Food Hampers', 'Food Hampers'), ('Chocolates', 'Chocolates'), ('Wallets', 'Wallets'), ('Cardholders', 'Cardholders'), ('Tote', 'Tote'), ('Trouser', 'Trouser'), ('PPE-Kit', 'PPE-Kit'), ('Mask', 'Mask'), ('T-Shirt', 'T-Shirt'), ('Recogonition', 'Recogonition'), ('Gym Set', 'Gym Set'), ('Fitness Bands', 'Fitness Bands'), ('Accessories', 'Accessories'), ('Pens', 'Pens'), ('Dairy & Organizer', 'Dairy & Organizer'), ('Bags', 'Bags'), ('Home Decor', 'Home Decor'), ('Jacket', 'Jacket'), ('Desktop', 'Desktop'), ('Medal', 'Medal'), ('Sleeves and Slipcases', 'Sleeves and Slipcases'), ('Kurtha', 'Kurtha'), ('Sweets and Dry Fruits', 'Sweets and Dry Fruits'), ('Home Accessories', 'Home Accessories'), ('Festive Gift Combo', 'Festive Gift Combo'), ('Handwash', 'Handwash'), ('Appliances', 'Appliances'), ('Generals', 'Generals'), ('Crossbody & Messenger Bags', 'Crossbody & Messenger Bags'), ('Premium Metal', 'Premium Metal'), ('Gift Bags', 'Gift Bags'), ('Button Buddies', 'Button Buddies'), ('Backpack', 'Backpack'), ('Cap', 'Cap'), ('Inspirational', 'Inspirational'), ('Home Utilities', 'Home Utilities'), ('Hot & Cold Flasks', 'Hot & Cold Flasks'), ('Sports Trophy', 'Sports Trophy'), ('Duffles', 'Duffles')], max_length=50)),
                ('subcategory', models.CharField(choices=[('Jean', 'Jean'), ('Formal Pant', 'Formal Pant'), ('Customized T-Shirts', 'Customized T-Shirts'), ('Dry Fit', 'Dry Fit'), ('Polo With Tipping', 'Polo With Tipping'), ('Round Neck', 'Round Neck'), ('Bomber Jacket', 'Bomber Jacket'), ('Wind Cheater', 'Wind Cheater'), ('NA', 'NA'), ('Polo', 'Polo'), ('Track Pant', 'Track Pant')], max_length=50)),
                ('related', jsonfield.fields.JSONField(null=True)),
                ('brand', models.ForeignKey(default='NA', on_delete=django.db.models.deletion.SET_DEFAULT, to='core.brand')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('option', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('pin', models.IntegerField()),
                ('address_line_1', models.TextField(max_length=100)),
                ('address_line_2', models.TextField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=60, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
        ),
    ]
