apparel_gender_category = (
    ("Male", "Male"),
    ("Female", "Female"),
    ("Unisex", "Unisex"),
)

apparel_category = (
    ("Cap", "Cap"),
    ("Formal Shirt", "Formal Shirt"),
    ("Jacket", "Jacket"),
    ("Trouser", "Trouser"),
    ("Short", "Short"),
    ("T-Shirt", "T-Shirt"),
    ('Gym Set', 'Gym Set'),
    ('Kurtha', 'Kurtha'),
    ('Security Uniforms', 'Security Uniforms')
)

apparel_sub_category = (
    ("Bomber Jacket", "Bomber Jacket"),
    ("Wind Cheater", "Wind Cheater"),
    ("Dry Fit", "Dry Fit"),
    ("Polo", "Polo"),
    ("Polo With Tipping", "Polo With Tipping"),
    ("Round Neck", "Round Neck"),
    ("Formal Pant", "Formal Pant"),
    ("Track Pant", "Track Pant"),
    ("Jean", "Jean"),
    ("Customized T-Shirts", "Customized T-Shirts"),
    ("NA", "NA"),
)

# this should contain all the categories of each type of products
categories = {
    ("Cap", "Cap"),
    ("Formal Shirt", "Formal Shirt"),
    ("Jacket", "Jacket"),
    ("Trouser", "Trouser"),
    ("Short", "Short"),
    ("T-Shirt", "T-Shirt"),
    ('Gym Set', 'Gym Set'),
    ('Kurtha', 'Kurtha'),
    ('Security Uniforms', 'Security Uniforms'),
    ("Frames", "Frames"),
    ("Sports Trophy", "Sports Trophy"),
    ("Inspirational", "Inspirational"),
    ("Medal", "Medal"),
    ("Plaques", "Plaques"),
    ("Premium Metal", "Premium Metal"),
    ("Salvers", "Salvers"),
    ("Recogonition", "Recogonition"),
    ("Trophy-Fiber", "Trophy-Fiber"),
    ("Backpack", "Backpack"),
    ("Crossbody & Messenger Bags", "Crossbody & Messenger Bags"),
    ("Duffles", "Duffles"),
    ("Hand Bagags", "Hand Bagags"),
    ("Laptop Bags", "Laptop Bags"),
    ("Overnighters", "Overnighters"),
    ("Rollers", "Rollers "),
    ("Sleeves and Slipcases", "Sleeves and Slipcases"),
    ("Strolley", "Strolley"),
    ("Tote", "Tote"),
    ("Travel Accessories", "Travel Accessories"),
    ("Hot & Cold Flasks", "Hot & Cold Flasks"),
    ("Mugs", "Mugs"),
    ("Sippers", "Sippers"),
    ("Water Bottles", "Water Bottles"),
    ("Accessories", "Accessories"),
    ("Bags", "Bags"),
    ("Office & Desktops", "Office & Desktops"),
    ("Plants", "Plants"),
    ("Pouches", "Pouches"),
    ("Bluetooth Speakers", "Bluetooth Speakers"),
    ("Earphones", "Earphones"),
    ("Fitness Bands", "Fitness Bands"),
    ("Gadgets", "Gadgets"),
    ("Headphones", "Headphones"),
    ("Powerbanks", "Powerbanks"),
    ("Tech Accessories", "Tech Accessories"),
    ("Appliances", "Appliances"),
    ("Home Accessories", "Home Accessories"),
    ("Home Utilities", "Home Utilities"),
    ("Timekeepers", "Timekeepers"),
    ("Cardholders", "Cardholders"),
    ("Dairy & Organizer", "Dairy & Organizer"),
    ("Generals", "Generals"),
    ("Gift Sets", "Gift Sets"),
    ("Wallets", "Wallets"),
    ("Button Buddies", "Button Buddies"),
    ("Desktop", "Desktop"),
    ("Diary & Note Pads", "Diary & Note Pads"),
    ("Folders", "Folders"),
    ("Lanyards", "Lanyards"),
    ("Lapel Pins", "Lapel Pins"),
    ("Pens", "Pens"),
    ("Personal Gifts - Key chains", "Personal Gifts- Key chains"),
    ("Wellness Gifts", "Wellness Gifts"),
    ("Covid Kit", "Covid Kit"),
    ("Handwash", "Handwash"),
    ("Mask", "Mask"),
    ("Sanitizer", "Sanitizer"),
    ("PPE-Kit", "PPE-Kit"),
    ("Others", "Others"),
    ("Aroma Candles", "Aroma Candles"),
    ("Chocolates", "Chocolates"),
    ("Cookies and Cakes", "Cookies and Cakes"),
    ("Festive Gift Combo", "Festive Gift Combo"),
    ("Flowers & Plants", "Flowers & Plants"),
    ("Food Hampers", "Food Hampers"),
    ("Gift Bags", "Gift Bags"),
    ("Gift Packaging", "Gift Packaging"),
    ("Home Decor", "Home Decor"),
    ("Sweets and Dry Fruits", "Sweets and Dry Fruits"),

}

order_status = (
    ("created", "created"),
    ("opened", "opened"),
    ("packing", "packing"),
    ("ready to ship", "ready to ship"),
    ("shipped", "shipped"),
    ("delivered", "delivered")
)

sub_categories = {
    ("Bomber Jacket", "Bomber Jacket"),
    ("Wind Cheater", "Wind Cheater"),
    ("Dry Fit", "Dry Fit"),
    ("Polo", "Polo"),
    ("Polo With Tipping", "Polo With Tipping"),
    ("Round Neck", "Round Neck"),
    ("Formal Pant", "Formal Pant"),
    ("Track Pant", "Track Pant"),
    ("Jean", "Jean"),
    ("Customized T-Shirts", "Customized T-Shirts"),
    ("NA", "NA"),
}

award_category = (
    ("Frames", "Frames"),
    ("Sports Trophy", "Sports Trophy"),
    ("Inspirational", "Inspirational"),
    ("Medal", "Medal"),
    ("Plaques", "Plaques"),
    ("Premium Metal", "Premium Metal"),
    ("Salvers", "Salvers"),
    ("Recogonition", "Recogonition"),
    ("Trophy-Fiber", "Trophy-Fiber"),
)

product_types = (
    ("Apparels", "Apparels"),
    ("Awards & Recognition", "Awards & Recognition"),
    ("Bags & Luggage", "Bags & Luggage"),
    ("Electronics", "Electronics"),
    ("Combo", "Combo"),
    ("Office & Stationary", "Office & Stationary"),
    ("Premium Gifts", "Premium Gifts"),
    ("Promotional Gifts", "Promotional Gifts"),
    ("Leather & Leatherites", "Leather & Leatherites"),
    ("Homeware", "Homeware"),
    ("Drinkware", "Drinkware"),
    ("Festivals", "Festivals"),
    ("Covid-19", "Covid-19"),
    ("Eco Friendly", "Eco Friendly"),
)